### PR TITLE
omit fade = TRUE in enter/exit functions due to API change, fixes #29

### LINKED ISSUE #29: gganimate API has changed for enter_ and exit_ functions
https://github.com/ropenscilabs/learngganimate/blob/20ac7b3039885321f35bb781e447f71d0944870e/coolcoolcool.Rmd#L41
The code now fails if the most recent commits of gganimate are installed from github.
The API has changed and `enter_grow` no longer has an argument `fade = TRUE` .
Many of our example will likely fail if users have a newwer installation of gganimate than we were using at ozunconf. Thrills and spills of using an in development package. I will update the line above.  And try to work though the other examples - doing a search for enter and exit should be easy enough. might be a good time to create a branch to update throughout the document.  May need a reference to the gganimate commit that the examples work with on the front page

### PR DESCRIPTION
**Pull request by tylerlittlefield**
Shoot, I forgot to create another branch for the heart pumping example. Let me know if I should just rename the title of this issue to reflect the fixes, or separate these two commits into two separate branches.

### CODE REVIEW

**Comment by adam-gruer** [comment]
> Shoot, I forgot to create another branch for the heart pumping example. Let me know if I should just rename the title of this issue to reflect the fixes, or separate these two commits into two separate branches.

No that's fine @tyluRp .  Thanks so much for helping out!

**Comment by adam-gruer** [comment]
And massive thanks for realising the fix for the `transformr` issue.  I came across that problem with one of the other examples, fixed but did not document 🤦‍♂️ .  I think I will add an issue and maybe an article about some of these little things relating to other packages - I know that not having the CRAN version of `tweenr` also caused our team issues.

**Comment by tylerlittlefield** [comment]
@adam-gruer Happy to help!

**Comment by adam-gruer** [comment]
So appreciated, I've added you to our list of contributors

**Comment by tylerlittlefield** [comment]
Awesome, I appreciate the "good first issue" tags. Really helpful for people like myself who are just starting to contribute to open source projects 👍

**Pull request merged**
